### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by miradnan** [somleng/somleng-adhearsion#123]
When I run the docker image, it doesn't load app/config.ru file. Is there is a sample file? 

The `docker-compose up` command fails and goes into an infinity loop looking for the app/config.ru file.

**Comment by dwilkie** [comment]
Hello, we just finished a rewrite of Somleng.

Please follow the getting started documentation to get somleng up and running on your local machine.

https://github.com/somleng/somleng-project/blob/master/docs/GETTING_STARTED.md
